#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ControllerApp.Resource", IsApplication=true)]

namespace ControllerApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int theme_devicedefault_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060026
			public const int accessPinEditText = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int closeValve = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int labelLamp = 2131099665;
			
			// aapt resource value: 0x7f060005
			public const int labelLastUpdate = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int labelValve = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int labelWaterPump = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int openValve = 2131099670;
			
			// aapt resource value: 0x7f060024
			public const int phoneNumber = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int relativeLayout1 = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int resetButton = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int submitButton = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int tableLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int tableLayout2 = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int tableRow1 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int tableRow3 = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int tableRow4 = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int tableRow5 = 2131099672;
			
			// aapt resource value: 0x7f06001c
			public const int tableRow6 = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow7 = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow8 = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int tankBar = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int textView11 = 2131099666;
			
			// aapt resource value: 0x7f060025
			public const int textView2 = 2131099685;
			
			// aapt resource value: 0x7f060004
			public const int textView21 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textView23 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int textView25 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int textView29 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int textView32 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int textView34 = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int textView35 = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int textView36 = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int textView37 = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int turnOffLamp = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int turnOffPump = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int turnOnLamp = 2131099678;
			
			// aapt resource value: 0x7f06001a
			public const int turnOnPump = 2131099674;
			
			// aapt resource value: 0x7f060020
			public const int update = 2131099680;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int ControllerLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int SetupLayout = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f03000d
			public const int button_cancel = 2130903053;
			
			// aapt resource value: 0x7f03000c
			public const int button_no = 2130903052;
			
			// aapt resource value: 0x7f03000f
			public const int button_reset = 2130903055;
			
			// aapt resource value: 0x7f03000e
			public const int button_update = 2130903054;
			
			// aapt resource value: 0x7f03000b
			public const int button_yes = 2130903051;
			
			// aapt resource value: 0x7f030002
			public const int command_canceled = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int command_sent = 2130903041;
			
			// aapt resource value: 0x7f030011
			public const int controller_number = 2130903057;
			
			// aapt resource value: 0x7f030003
			public const int message_warning = 2130903043;
			
			// aapt resource value: 0x7f030010
			public const int setup_done = 2130903056;
			
			// aapt resource value: 0x7f03000a
			public const int sms_command_close_lamp = 2130903050;
			
			// aapt resource value: 0x7f030005
			public const int sms_command_close_valve = 2130903045;
			
			// aapt resource value: 0x7f030008
			public const int sms_command_close_water_pump = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int sms_command_open_lamp = 2130903049;
			
			// aapt resource value: 0x7f030004
			public const int sms_command_open_valve = 2130903044;
			
			// aapt resource value: 0x7f030007
			public const int sms_command_open_water_pump = 2130903047;
			
			// aapt resource value: 0x7f030006
			public const int sms_command_status_report = 2130903046;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
